// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCBTWFB5bgVXVayrlQCUKUlDKbtGuy3Pg',
    appId: '1:405252637540:web:79fdd49b07e7b030277071',
    messagingSenderId: '405252637540',
    projectId: 'aidrona',
    authDomain: 'aidrona.firebaseapp.com',
    storageBucket: 'aidrona.firebasestorage.app',
    measurementId: 'G-L0KDS1LG2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB0keCjPD_KGDd7NB9a7ZMxys-A0-1gkc',
    appId: '1:405252637540:android:ecb92a56862d0e0b277071',
    messagingSenderId: '405252637540',
    projectId: 'aidrona',
    storageBucket: 'aidrona.firebasestorage.app',
  );
}
